sudo: required
services:
  - docker

before_install:
  - docker build -t abdullmm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run abdullmm/react-test npm test -- --coverage

after_success:
  - docker build -t abdullmm/multi-client ./client
  - docker build -t abdullmm/multi-nginx ./nginx
  - docker build -t abdullmm/multi-server ./server
  - docker build -t abdullmm/multi-worker ./worker